### ISSUE TITLE
Encoding Fails as soon as I press e

### ISSUE THREAD

**Issue by radar-duker** [ekisu/mpv-webm#119]
The below issue is resolved. Now I am having an issue where encoding fails as soon as I press e. Please see my latest post.

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

mpv.net-5.4.9.0-portable on Windows 10 (this doesn't work with standard MPV either following the same steps)

## Description

I added webm.lua to [mpv folder]/portable_config/scripts. I changed keybind to "E".

I added webm.conf to [mpv folder]/portable_config/script-opts. I changed keybind to E.

The two folders scripts and script-opts also exist identically in C:\Users\[user]\AppData\Roaming\mpv\ in case mpv is not picking up portable_config (even though I know it is because it loads my config).

Nothing happens when I press E. In the console, it says E is not binded to anything.

## Log file

Here is the log file. I loaded a video and pressed lowercase e and capital E a bunch of times and nothing happens.

https://drive.google.com/file/d/1_SEM9wnTjm8AKr58v_As5rPNPl3nx5oF/view?usp=sharing

**Comment by radar-duker** [comment]
I reverted the keybind to capital W and it is still not working. Just in case that may be suggested as the problem.

**Comment by radar-duker** [comment]
I was able to fix my initial problem by adding "w script-binding webm/display-webm-encoder" to input.conf. Now I have an issue where it says encoding fails as soon as I press e to encode. Log attached.

https://pastebin.com/2fV97qrD

**Comment by ekisu** [comment]
This script does not work with mpv.net, because it uses mpv's encoding capabilities, which are not exposed by mpv.net (at least as far as I know). One way out would be using the [ffmpeg branch](https://github.com/ekisu/mpv-webm/tree/ffmpeg-support), which does not rely entirely on mpv (but is long unmaintained), or using other encoding scripts, like [this one](https://github.com/occivink/mpv-scripts).

The first bug (the script's interface not showing after pressing the keybind) seems to be a [known issue](https://github.com/stax76/mpv.net/issues/271). I'll close this issue, as the only way of supporting mpv.net is to use an external dependency, which kind of defeats the point of the script - "no external dependencies"; feel free to reopen if you need to.
