### ISSUE TITLE
Please help a newbie.

### ISSUE THREAD

**Issue by palunglaut** [ekisu/mpv-webm#41]
Where is the "script" folder ?

I usually just use mpv for watching movies, and i dont find the "script" folder in my mpv directory. And i cant find this ~/.config/mpv/scripts/ location.

**Comment by davste0816** [comment]
If you’re on windows, there will be a folder under C:\Users\”Your user name”\AppData\Roaming\ thats called mpv. Make a new folder inside of the mpv folder and call its scripts. Drop the lua file in there and you’re all good to go.

**Comment by ekisu** [comment]
What @davste0816 said is pretty much it, did it work for you?

You could also create a `mpv/scripts` folder in the same directory as the `mpv.exe` executable (assuming you're running Windows), and place the script there.

**Comment by milanbt** [comment]
I learned from this thread that the path for scripts that you have to make is: ~/.config/mpv/scripts. It would be very helpful if the common scripts directory location was in the README. I tried google searching "mpv scripts directory linux" and I couldn't find anything.

**Comment by ereinstein** [comment]
https://mpv.io/manual/master/#configuration-files

It's right there in the mpv manual.

**Comment by milanbt** [comment]
I guess I was a little impatient in searching, because the mpv manual does show up on DDG but not google in the top page and the answer is also in the arch wiki. 

I still think a bit of redundancy or even a link to the manual on the README would help less savvy users install it. I once wanted to install this script a few years ago, but just gave up because I didn't know where the script directory was and wouldn't have thought to read the mpv manual.

**Comment by ekisu** [comment]
Added some info about this on the README
