### ISSUE TITLE
Issue with default inputs

### ISSUE THREAD

**Issue by Chadwiick** [ekisu/mpv-webm#56]
## mpv version and platform

```
mpv version 0.29.1 (current)
Windows
```

## Description

Currently I am using the line: `--no-input-default-bindings`

What I'd like to do is add a command in the input.conf to change the current webm default hotkey (Shift+W). That way I can use my no input command again (I like to have only a few hotkeys active to avoid accidentally pressing one). Any help is appreciated, thanks :)

**Comment by OrangeChannel** [comment]
You'd want to add `S script-binding webm/display-webm-encoder` for the webm keybind to be switched to "S" for example. In order to disable all of the other stuff you have in input.conf when running with `--no-input-default-bindings`, put the script-binding line at the very top, and underneath it add this: `default-bindings start`. This will make it so all of the following input lines will be read as default bindings, which mpv will disable once it runs `--no-input-default-bindings`. (I hope I understood your problem right.)

**Comment by Chadwiick** [comment]
Your my hero, thanks so much! Works perfectly for what I'd like to do.

If I may ask one last question, is there a way to disable the script from saving subtitles in the encode options? Ideally I'd like to add the ability to create a toggle function within the webm.lua script to choose if subtitles are added to the webm (yes - keeps subs, no - saves without subs). By default, I don't find much use in keeping subtitles in my webm files. I'm still learning how to script, so all the help so far has been greatly appreciated.

**Comment by ekisu** [comment]
Press "v" to hide the subs, and then encode.

**Comment by Chadwiick** [comment]
Weird, that never used to work but it literally just worked now. My guess is maybe I disabled subs while I was in the webm maker instead of hiding the subs **then** opening webm maker. Either way, thanks for the reply!
